TrajectoryPlannerROS:
    max_vel_x: 0.2
    min_vel_x: 0.05
    max_vel_theta: 0.5
    min_vel_theta: -0.5

    min_in_place_vel_theta: 0.3

    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    acc_lim_y: 1.0

    xy_goal_tolerance: 0.10 
    yaw_goal_tolerance: 0.15
    holonomic_robot: false

    path_distance_bias: 0.7

controller_patience: 20
planner_patience: 20
recovery_behavior_enabled: true
