obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.30
# inflation_radius: 1.2
cost_scaling_factor: 20.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
